### ISSUE TITLE
Potential issue with identically named functions in both the test framework & simulator.

### ISSUE THREAD

**Issue by tomhartley** [m8pple/arch2-2015-cw1#11]
[Just discovered by cross-checking code & sim with someone else] -

If two functions happen to be named exactly the same in the test & simulator files, the linker will fail with a 'duplicate symbol' warning. How should we avoid this? 

Potential solution: Define 2 namespace prefixes for test & simulator to prefix all functions with - however that could be a pain for everyone to do. Another solution is just to hope it doesn't happen, but with simple function names for example 'init' this is optimistic at best.

**Comment by m8pple** [comment]
So you mean if someone defines a utility function like `big_to_little` on the
CPU side, and someone else happens to have defined the same function
on the test side?

Hrmm, interesting. So there are a number of possible solutions (some of
these are more advanced than the C++ we are currently teaching you,
but it is nice to know the options):
- C: Use prefixes like `cpu_` and `test_`. This is a pretty good strategy in C,
  and is commonly used.
- C: mark the functions [`static`](http://stackoverflow.com/questions/558122/what-is-a-static-function),
  which means they are not visible outside the current file. Note that there is a difference between
  a static function in the C sense (not visible outside the source file), and a static member function of
  a class (shared amongst all instances of class).
- C++: use unique namespaces like `test` and `simulator`. I would be inclined to choose a prefix unique
  to yourself (e.g. your login), rather than `test` and `simulator`. You could then use the
  inline method below to ensure the definitions don't conflict.
- C++: use [`inline` functions](https://en.wikipedia.org/wiki/Inline_function) defined in a shared
  header. It is legal to have multiple definitions of one `inline` function as long as they are
  the same. This solves the case of wanting to share one utility function between your tester
  and cpu, but not the case where you want to avoid conflicts with another definition with
  the same name.
- C++: use [unnamed namespaces](http://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces). This
  gives the functions in the unnamed namespace unique linkage, so they will not conflict with
  identically named functions in other source files (you'll get one copy of each, but internally
  they have a different name. Its a bit weird.)

For functions called `init`, I would strongly suggest using the `static` method. It is almost
guaranteed that you don't want anyone outside of the current file being able to call that
function. If you need it to be shared between two source files via a header (so you
can't make it `static`), then a name like `init` or `reset` is just asking for trouble. It is
has public linker-scope, even if it isn't part of the public API, so you need to defend
against people accidentally linking against it. Some sort of prefix is needed in that case.

Leaving this open in case there are any more comments.

**Comment by fyquah** [comment]
`static` and `inline` wouldn't be really practical - I can have various classes / fnc in different files and I'd want external linkages for them throughout my CPU.

A potential problem I can foresee with unnamed namespace is global buffers - several objects might be communicating using global buffers. We will end up moving that variable / object to the global space for external linkage and end up with the same problem.

Assuming the possibility of using the namespace / prefix `test` in the simulator, would it make sense to `namespace` or prefix every external linkage with `test` or `test_`?

(And yes, the name clash was indeed an `init`)

**Comment by m8pple** [comment]
_cough, splutter_ Global buffers! Global buffers!!!!

You have a perfectly good CPU state, why can't everything go in there.

Or if you _really_ want globals, you could always make them global static
members of a class with a namespace you choose?

> Assuming the possibility of using the namespace / prefix test in the simulator,
> would it make sense to namespace or prefix every external linkage with test or test_?

Do you mean ignoring the possibility or assuming? 

I'd assuming using `test_` as a prefix is reasonably safe, particularly if you wrap
all your private code in a namespace.

Note: I think you might be over-estimating the probability of conflicts here. `init` is
indeed likely to clash, but in all the submissions last year I didn't get a single
name clash between testers and CPUs of different people.

**Comment by fyquah** [comment]
I am suggesting In case it happens. I do agree that global buffers are bad.

I meant `test_` prefix of `test` namespace should work fine, so long no CPU uses it.

**Comment by m8pple** [comment]
Resolved - closing to prepare for prepare for new archinauts.
