### ISSUE TITLE
makefile points to wrong sources

### ISSUE THREAD

**Issue by lorenzo2897** [m8pple/arch2-2015-cw1#21]
The spec defines three options for the paths of source files that get compiled into the program, of which one is `src/[your_login]/mips_cpu_*/*.cpp`
However, the makefile contains the line `$(wildcard src/$(LOGIN)/mips_cpu/*.cpp)`
The two do not match (the makefile is missing a wildcard in the directory name).

The same goes for the test suites (`test_mips_*/*`).

Also, I noticed that the _mips_cpu.c_ skeleton from 2014 is indeed a C file, which wouldn't get compiled according to the spec (which only allows cpp). It's a minor thing, but maybe the makefile could be set to include C files as well as C++?

**Comment by m8pple** [comment]
Sorry, I mentioned these in the tutorial, but didn't directly address them.

I agree - the pattern in the spec does not match. In order to try to go for a
non-breaking change, I've added the pattern that matches the spec, as
well as the original (erroneous) one.

As for why I changed things - there is a tendency for students to see C and C++ as
fundamentally different things, and I wanted to get away from that idea. In previous
years I opened up both possibilities (don't really want to constrain people), but
I think that didn't help. For those who want to write in C, it makes more sense
to recognise that they can do the same thing in C, as long as they choose to
forgoe (sp?) the conveniences of C++. So it requires them to understand what
is C and what is C++ in a more explicit way.

This is part of tackling a general perception of C++ as less efficient than C,
when in reality C++ is exactly as efficient as C, as long as you don't use any
of the additional C++ abstractions. In the embedded systems world this is
becoming an issue, as the productivity benefits of C++ for large-scale
programs are outweighing the (possible) performance issues. A good engineer
should be able to pick and choose the C++ features, understanding the
performance implications.

It's interesting that languages like [Rust](https://www.rust-lang.org) have grown
up to try and adress exactly this (real or percieved) drawback, and are trying
to do abstraction with zero abstraction.

Longer answer than needed, but it's (hopefully) useful for students to understand
why we pick particular languages or goals.

(Also up for debates about these things - it is quite an interesting discussion :)
