### ISSUE TITLE
Should we made unused bits don't cares or return an error if they are nonzero?

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#27]
In the ISA documentation, bits 6-10 are shown as 0s, but they are not used at all by the instruction - are these don't cares or should putting 1s in these bytes result in an InvalidInstruction error?
![image](https://cloud.githubusercontent.com/assets/17267419/19495410/2aa0e7a4-957b-11e6-9ada-3bdc249237a0.png)

**Comment by m8pple** [comment]
To be absolutely correct, yes - the simulator should return an InvalidInstruction error.
Practically speaking, I'm more interested in getting the main functionality working
rather than handling corner cases.

A real processor should throw an exception, because those bits might eventually
be used to encode or indicate something else (e.g. in a future revision of the ISA).
So if the CPU encounters an instruction that doesn't fit in their version of the
ISA, they should except (the exception handler might be able to implement
the instruction in software, albeit more slowly)

**Comment by ps-george** [comment]
Okay, thanks, I'll throw an exception.

**Comment by ps-george** [comment]
Your CPU treats these bits as don't cares, so has failed all my tests checking that it will throw exceptions when these bits are set, does this just mean my tester is very specific but not intrinsically wrong, since the MIPS spec specifies the bits should be 0?

**Comment by m8pple** [comment]
Nope, it means that there is a bug in my reference CPU. I thought I added tests for
all the don't cares, but apparently not (I may have had a regression).

I'll look into this and update my reference CPU.

**Comment by fpgamy** [comment]
May I ask what is the difference between scenarios when an invalid argument error and an invalid instruction exception should be thrown?

**Comment by m8pple** [comment]
An invalid argument is in the group of errors relating to the API. It is signalling
that the user is using the API incorrectly (e.g. trying to write register 1000).

An invalid instruction exception is from within the simulated processor - the
API is being used correctly, but it is signalling that an event has happened
with the CPU that needs to be handled in some way.
