### ISSUE TITLE
Are registers big endian?

### ISSUE THREAD

**Issue by fpgamy** [m8pple/arch2-2015-cw1#31]
For the load word and store word operation, do we assume the registers are big endian (and the memory is little endian, therefore we have to convert to and from big endian for load and store)?

**Comment by m8pple** [comment]
This gets to the heart of what endian-ness is, which is why I chose a big endian MIPS :)

If you consider variables in your program, these will typically get mapped
into registers (though they may live on the stack; it doesn't matter here). So
if you do:

```
uint32_t x=0xFF000000ul;
x = x>>24;
if( x==0xFF){
    std::cerr << "yes\n";
}else{
    std::cerr << "no\n";
}
```

It's worth asking yourself the question: "will the program print something different on a big-endian versus little-endian architecture?"

If we now change that to:

```
uint8_t x_as_bytes[4]={0xFF, 0x00, 0x00, 0x00};
uint32_t *ptr_to_x = *(uint32_t*) bytes; // cast pointer from uint8 to uint32
uint32_t x = *ptr_to_x; // Read from the pointer to uint32_t
x = x>>24;
if( x==0xFF){
    std::cerr << "yes\n";
}else{
    std::cerr << "no\n";
}
```

Does that print something different on little-endian versus big-endian?

The key thing about endianness is the mapping of multi-byte integers to
individual bytes. Inside the processor an integer is just an integer - there
are no individual bytes. Any manipulation you do on the integer works
purely in terms of integers, including bit-shifts, masks, etc.

Outside the processor (in RAM) there are only individual addressable
bytes - there are no integers. True, the data-bus may be 32-bits wide,
but that only means that you can read/write up to 4 bytes at the
same time, it doesn't say anything about how they are interpreted
as multi-byte integers.

So to answer your original questions:
- "do we assume the registers are big endian" - that question isn't really meaningful :)
- "and the memory is little endian, therefore we have to convert to and from
  big endian for load and store" - certainly loads and stores are the key place where
  you have to convert, but you are not converting from one endianess to another,
  rather you are taking an integer and making it is stored as big-endian ordered
  bytes.

So if you think about anywhere that data enters the CPU from memory (instr fetch,
data read), or leaves the CPU (data write), those are the precise places where you
need to worry about endianness.

**Comment by louiskueh** [comment]
Would it be right in saying that if we write our instructions in a 32 bit binary number e.g.

0b00000000001000100001100000100100

then we would not have to worry about the endianess since its a pointer pointing to only one location?

**Comment by m8pple** [comment]
If you do:

```
uint32_t x=0b00000000001000100001100000100100ul;
```

Then there is no need to worry about endianess (it's an integer,
and endianness doesn't apply).

However, if you write that integer into memory as a sequence of bytes:

```
mips_mem_write(hMem, addr, 4, *(uint8_t*)&x);
```

then it will end up in the endianness of the CPU your simulator is
running on (presumably little-endian). This is probably not what
you want.

(Not recommended:) You _could_ manually rearrange the bytes in the constant:

```
// This is the byte-reversed form of x
uint32_t rev_x=0b00100100000110000010001000000000ul;
```

   // Note that:
  ((x>>26)&0xFF) != ((rev_x>>26)&0xFF)

which would mean that the integer was no longer the same, but
when written to memory by a little-endian machine it would end up
in big-endian. But this is still not portable.

It is much better to work with integers in the natural form for the
CPU, and just convert the endianess only at the point that you
read and write to byte-oriented storage (i.e. memory).

**Comment by louiskueh** [comment]
I am still a little confused on how the processor is little endian and how mips is big endian

For example in the tester side I wrote to memory the instruction : instr  = 00....10001(using 32 bits)

```
err= mips_mem_write(mem,pc,4,(uint8_t*)&instr)
cout<< instr << endl;
```

and in the cpu side read the memory and placed the instruction into currentinst

```
err=mips_mem_read(state->mem,state-pc,4,(uint8_t*)&currentinst
cout << "cpu instr "<< currentinst << endl;
```

I then outputted the instructions in both cpu and tester and obtained the same value without performing any rearranging of the bits

Am I doing something wrong here?

**Comment by m8pple** [comment]
If both the tester and the CPU read and write things in the same endianess,
then it will work (even if it is incorrect). But, if your tester writes the values
to memory in little-endian (incorrectly), and somebody elses CPU reads the
values back in big-endian (correctly), then the CPU will receive a garbled
instruction.

**Comment by fpgamy** [comment]
Sorry for bringing this up again, but if I load a byte from memory during testing should I only use an address which is aligned to the block size (4)?

(Storing the word 0x12345678 at address 0 would result in:
`address0: 0x12, address1: 0x34, address2: 0x56, address3: 0x78`
for little endian
and 
`address0: 0x78, address1: 0x56, address2: 0x23, address3: 0x12`
for big endian. Would trying to load a byte from address 1 result in a pass/failure depending on the endian-ness?)
