### ISSUE TITLE
Is return address set unconditionally or conditionally for bltzal and bgezal?

### ISSUE THREAD

**Issue by Carotti** [m8pple/arch2-2015-cw1#34]
The [documentation](http://www.cs.cmu.edu/afs/cs/academic/class/15740-f97/public/doc/mips-isa.pdf) seems a little bit unclear about whether or not `bltzal` and `bgezal` set the return address even if the branch isn't taken. The wording seems to imply that it does, which doesn't make much sense to me (if this is the case... why is that useful? Or is it a hardware limitation?).

On the same note, I have tested in _Spim_ which sets R31 unconditionally and in _Mars_ which sets it conditionally. Is this another case of simulators being inconsistent/wrong?

**Comment by m8pple** [comment]
My reading is that the return address is always set, even if the branch is not taken. In particular,
the "Operation" section says that register 31 is set in step I, and the branch then possibly happens
in step I+1. (So Spim is right and Mars is wrong).

There are a few reasons why it is defined that way. One is to think about the advantages
of setting it conditionally - how would it help?

I suppose on possibility is that you could leave a value in register 31, which would only be
modified if the branch was not taken. Maybe that gives you one extra register to play with,
but only in the case that the branch was not taken - it's quite a difficult thing to optimise
for (though not impossible). You could also use 31 as a flag for whether the function was
called or not, starting with $31=0 to indicate "not taken", then it will be set to something
if it is taken. But how would you use this value? Presumably the same information is available
in the register which was used for the branch condition.

In terms of why it helps to have it be set unconditionally, the first is that it makes the
data-path easier to build. In order to implement this instruction we'll need to add a
connection from PC+4 (already in our data-path), through another special-purpose +4,
and into the register file write data input. Adding a conditional write simply adds
overhead on the control decode. It's not especially difficult for single-cycle, but in
a pipelined processor it means we need to conditionally change a control-flag quite
late in the pipeline.

Having it unconditionally set $31 also makes it easier to reason about the program.
The compiler knows that the local register state when the program reaches PC+8
will be the same, regardless of how it got there, which makes optimisations easier
(otherwise you'll have an explosion of states to manage). Any reasonable compiler
(from the 70s) would quite likely just assume that register $31 would not
maintain it's value and contained an "unknown" value,  in order to avoid an exponential
explosion of possible register states they need to track. At least this way they _know_
that it will contain PC+8.

(Modern compilers could actually track that explosion of states, and possibly
exploit it, and the data-path aspect matters less in a super-scalar CPU. But
these were decisions taken a long time ago. However, RISC-V, which is a modern
RISC ISA is even simpler: https://riscv.org/)
