### ISSUE TITLE
MFHI

### ISSUE THREAD

**Issue by ZoeSlattery** [m8pple/arch2-2015-cw1#38]
When trying to implement MFHI, is it possible to define a new 'reghi' register when creating a cpu and if so does this need a special name? Otherwise in the tester side of it I would like to set a specialised reghi register to be a value, then try and move it to a new register using my function and read from this new register but without a standardised name I don't see how this will work with other people's cpus?

**Comment by m8pple** [comment]
You can certainly define a new reghi (and presumably reglo) register inside your
CPU. Well you probably _should_ do that, as it is part of the user-visible state of
the ISA.

However, I'm afraid you can't directly expose it to the users of the CPU
(by design - insert evil cackling here). The only way that a user can interact
with your hi and lo registers is via sequences of instructions that they place
in memory, and the general purpose registers that they _can_ access.

This relates to #40.
