### ISSUE TITLE
LWL

### ISSUE THREAD

**Issue by ZoeSlattery** [m8pple/arch2-2015-cw1#39]
Hi, I was just wondering if there was a clearer description of LWL than that given inmath-atlas.sourceforge.net/devel/assembly/mips-iv.pdf
as I don't understand what they mean by the least significant part of the word in the register is unchanged? Cheers

**Comment by ps-george** [comment]
Bits `15:0` of the destination register are unchanged, bits `31:16` are filled with the 16 bits from memory.

So if you had this word (4 bytes) in your register: `0x12345678`, and you loaded `0x9999` from memory, the final value in the register would be 0x9999**5678**. The least significant part of the word in the register has not changed.

**Comment by ZoeSlattery** [comment]
So in LWL do you not load 4 bytes from memory, is it just 2?

**Comment by ps-george** [comment]
Yep. I load all 4 bytes and then check which 2 bytes I need, but you could only load 2 from memory if you're less easily confused by endian-ness than I am.

**Comment by m8pple** [comment]
LWL and LWR are horrible instructions, both to implement and test.

Part of the difficulty is that they don't make so much sense in isolation.
The way that I dealt with it was to draw pictures of what happens in
the _pair_ of LWL and LWR instructions, as that tells me what the
individual instructions should be. I then manually created test-cases
for each offset (0,1,2,3) from the pictures. Then I could implement it
and be pretty sure that my implementation was doing the right thing.

For example, _pretend_ that there is an instruction called LWU which
can do loads from unaligned addresses, and it is fairly obvious what
should happen if you apply it at different byte offsets. Then expand
LWU into the pair of LWL and LWR and work out what each one must
do in order to have the same combined effect as LWU.

Regarding how many bytes to load - MIPS has a 32-bit address bus,
so in reality it will always read 4 (aligned) bytes, then select the ones
it needs. However, when writing a real address bus has byte-enables,
so it can choose which bytes of a 32-bit aligned word which actually
be written (these are what SWL and SWR would use).

**Comment by ps-george** [comment]
Do these instructions load 1, 2, 3 or 4 bytes depending on the offset? So an aligned LWL will load the whole word? What is the point of having the LW instruction if LWL will load the whole word when it's aligned?

**Comment by m8pple** [comment]
While LWL will load the whole word if it is aligned, it's purpose is for the cases
where you don't know it is aligned.

So if you know it is aligned:

```
lw $1, 0($2)
```

If you don't know it is aligned (updated as suggested by @ps-george and @Carotti):

```
lwl $1, 0($2)
lwr $1, 3($2)
```

So if you can prove it is aligned then one instruction, but if you're not sure you
have to take two instructions (even though it may be aligned).

So your argument is that we could just use lwl $1, 0($2) instead of the lw. On one
level that is true, and you could implement lw as just activating the lwl data-path
(I think) However, there are likely to be performance implications of selecting the
unaligned path (especially in a pipeline), so it is a good idea to be able to
distinguish.

**Comment by ps-george** [comment]
Is `0($2)` different for each instruction above? In my interpretation lwr would have to read from the `(effMemAdr for lwl) + 3` to get the whole word.

**Comment by Carotti** [comment]
@m8pple, The spec says that the effective address for LWR points to the least significant byte of an unaligned word though?

Surely to load an unaligned word, you would do:

`lwl $1, 0($2)`
`lwr $1, 3($2)`

**Comment by m8pple** [comment]
Ah, you're right - the main point I was trying to make is the
two vs one instruction thing.

Did I mention that I hate LWL and LWR?
