### ISSUE TITLE
PC after exception

### ISSUE THREAD

**Issue by divyanshmanocha** [m8pple/arch2-2015-cw1#43]
Sorry to bring this up again. It directly relates to issue #30, however I would like some more clarification. 
1. If the PC was not to be incremented should an exception occur, does that mean the instructions following the failed instruction will not run to preserve the current state?
2. Therefore in order to run the instructions that follow, the test file needs to force increment the PC if and when an exception occurs?

**Comment by m8pple** [comment]
No apologies needed.

Whether the instruction after the excepting instruction runs is entirely up to the
user of the CPU. In the example from #30, we could modify this:

```
while( mips_success == mips_cpu_step(hCPU) ) ;
```

into this:

```
 while(true){ mips_cpu_step(hCPU); } ;
```

This would mean that the user was trying to continually run instructions, but
once an exception occured, the CPU would try to execute the same instruction
over-and-over again. If there was a fault once, there will be a fault every
subsequent time. So yes, point 1 is correct - we cannot run the current
or following instructions in order to preserve the state.

However, a user could decide to do:

```
while(true){
    auto e = mips_cpu_step(hCPU);
    if( e==mips_ErrorArithmeticException ){
         uint32_t currPc;
         mips_cpu_get_pc( hCPU, &currPc );
         mips_cpu_set_pc(hCPU, currPc+4);
    }else{
         break;
     }
}
```

This would be somewhat akin to Visual Basic's appalling "On Error Resume Next" directive
(ok, I suppose there were some uses for it).

In some sense it is akin to the test file forcing the pc to increment, by skipping
instructions and making progress at any cost.
