### ISSUE TITLE
How do we test mips_cpu_free?

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#45]
Anything I do to the cpu pointer after I've 'freed' it crashes the program.

I've used `mips_cpu_impl *state = new mips_cpu_impl;` to create the cpu and `delete state` to free it.

I could use 'smart' pointers or `malloc` and `free`, but can't guarantee others will have done that, so testing their mips_cpu_free's will crash my program.

**Comment by m8pple** [comment]
> Anything I do to the cpu pointer after I've 'freed' it crashes the program.

That seems reasonable - it's the user's error, and is effectively uncheckable.
Even if you put a sentinel/magic value in your CPU state, you still can't check
whether the user hasn't done something wierd in all cases.

There is pretty much no way of testing that mips_cpu_free works without
setting up some kind of process isolation (you'd need to spawn
a process so that if their program crashes it doesn't take out your
entire tester). Way too much effort.

About the only thing I can think of is to create/free the CPU a billion
times and see if memory runs out, but that also leads to a crashing
situation.

So in this case it is very difficult to test all aspects of the API.
