### ISSUE TITLE
Previous Instruction Not Known

### ISSUE THREAD

**Issue by luisi-at** [m8pple/arch2-2015-cw1#46]
I've automated my test harness but now every time I pass `mips_test_begin_test` an operation mnemonic string, `ADD` for instance, the output displays that test has run successfully and then adds the warning that the previous instruction is not known:

![screen shot 2016-10-26 at 01 16 09](https://cloud.githubusercontent.com/assets/17338500/19708865/d26254fc-9b19-11e6-81f5-469637aa0e96.png)

The operation is quite clearly legal, so what's the problem? Am I right in thinking that the internal lookup uses an exact match for the string that goes in `mips_test_begin_test`?

**Comment by m8pple** [comment]
You can see the internal structure of the tester here:

```
https://github.com/m8pple/arch2-2016-cw/blob/master/src/shared/mips_test_framework.cpp#L227-L229
```

Basically it looks up the string in a set of known instruction names, and warns if it doesn't recongnise it.

Are you sure that the string you are passing only contains "ADD", so no whitespace or anything else?
It's noticeable that you seem to be missing the left-hand pipe on the line, but the format string:

```
"|%12s |   %4u |   %4u |  %5.1f%% |\n"
```

_should_ result in a string with a pipe then enough spaces to pad the instruction field.

In order to debug it you could put a break-point on the line 228, and see what the value actually
is.

**Comment by luisi-at** [comment]
Debugged as was suggested and I dumped the following to the terminal:

![screen shot 2016-10-26 at 17 51 52](https://cloud.githubusercontent.com/assets/17338500/19735795/ec11412a-9ba4-11e6-8785-051a0fd0098c.png)

So as can be seen, there is no whitespace, or other spurious characters, as the string length (4) matches exactly the number of characters in the string.

I am passing the string into `mips_test_begin_test` using `instruct.c_str()`. Could this be adding invisible formatting characters that I can't see? Or is there a better way to pass into the begin test function?

**Comment by m8pple** [comment]
Sorry, I still have no idea. I looked though that bit of your testing code, and nothing
immediately jumped out at me as being wrong. You're using c_str correctly,
and I can't see any specific problems.

If it causes a problem in the final testing then I'll go in and look into it further.
