### ISSUE TITLE
Final test

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#51]
I got a completely different output when I clone the git repository, put my source files in, and then make and run the program to the output shown from the self tests today. Are you sure you used the correct blackboard submission? (I've submitted several times?)

Failing that, are you using the latest version on Git?

I ask because it was almost as if it were someone else's code or CPU, there were printed bits of code where there are no corresponding fprintf or cerr statements in my code, and the result was completely different.

**Comment by ps-george** [comment]
On further examination, it looks like the output is testing someone else's CPU?

This could be intentional then if it's your soft test CPU..

**Comment by m8pple** [comment]
Hrmm, this is why i was wary about doing a full auto run, as i don't double check the output like i do for the soft and hard runs.

So its possible something went wrong.

In future i think i'll resist the pressure to do extra runs, as it doesn't necesarily help.

David Thomas

-------- Original message --------

**Comment by Carotti** [comment]
My test bench appeared not to like whichever CPU it was ran with during the test today, also. 

Upon further inspection, appears to be failing all the tests with invalid handle error - maybe because the tests weren't run with the latest version of the API (since I require 512MB of memory for testing J and JAL fully)? 

This would also explain why I fail all of my own tests (but pass all of yours!).

EDIT: I'd like to clarify that I'm not particularly bothered about this, as long as the final marking uses the latest version of the API!
